import Head from 'next/head';
import LayoutHoc from '../../hoc/Layout';
import {Cryptocurrencies} from '../../components';


export default function CryptocurrencyPage() {
    return (
        <>
        <Head>
           <title>Cryptocurrencies - Crypto Verse</title>
           <meta name="description" content="Generated by create next app" />
           <link rel="icon" href="/favicon.ico" />
       </Head>
       <LayoutHoc>
           <Cryptocurrencies simplified={false} />
       </LayoutHoc>
     </>
    )
}