import Head from 'next/head';
import LayoutHoc from '../../hoc/Layout';
import {News} from '../../components';

export default function NewsPage() {
    return (
        <>
        <Head>
          <title>News - Crypto Verse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
         <LayoutHoc>
            <News simplified={false} />
         </LayoutHoc>
      </>
    )
}
