import Head from 'next/head';
import LayoutHoc from '../../hoc/Layout';
import {Exchanges} from '../../components';


export default function ExchangesPage() {
    return (
        <>
         <Head>
            <title>Exchanges - Crypto Verse</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <LayoutHoc>
            <Exchanges />
        </LayoutHoc>
      </>
    )
}
