import Head from 'next/head';
import LayoutHoc from '../../../hoc/Layout';
import {CryptoDetail} from '../../../components';



export default function CryptoDetailPage(props) {
    const {name} = props;
    return (
        <>
        <Head>
           <title>{name} - Crypto Verse</title>
           <meta name="description" content="Generated by create next app" />
           <link rel="icon" href="/favicon.ico" />
       </Head>
       <LayoutHoc>
           <CryptoDetail />
       </LayoutHoc>
     </>
    )
}

export async function getServerSideProps(context) {
    const params = context.params;
    console.log(context.params)

    return{
        props:{
            name:params.coinId
        }
    }

}